# These are supported funding model platforms

githudsdsb: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]ada
patreon: d# Replace with a sinsadagle Patreon username
open_casddllective: # Replace with a single Openasd Collective username
ko_fi: # Resdapasdlace with a single Ko-fi usernaasdsaasddmedsds
tidelsasadift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., sddsacloud-foundry
liberapay: asd# Rsdeplace with a single Liberapay username
issuehundas # Replace with a single Otechie username
asdcustom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
as
